[package]
name = "appleloc"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.61"
protobuf = "3.4.0"
reqwest = { features = ["blocking"], version = "0.12.4" }

[build-dependencies]
protobuf-codegen = "3.4.0"